### PR TITLE
ണ = N?

### PR DESCRIPTION
**Pull request by vachan-maker**
I think its better to use 'N' for 'ണ' instead of n. People may confuse ന and ണ since both of them is assigned to the letter n. If the current way is right, I will close this PR.

### CODE REVIEW

**Comment by vachan-maker** [comment]
മണം - manam (current)
maNam (new)
വനം - vanam

**Comment by subins2000** [comment]
This is a good idea. You'll have to replace other instances of "ണ" too like "ണ്ണ".

**Comment by vachan-maker** [comment]
Sorry for closing the PR. I thought I did something wrong.

**Comment by vachan-maker** [comment]
Anything else that needs change?

**Comment by subins2000** [comment]
The rule changes are good, but this will break the unit tests here, should change its occurences of `ണ to N` too: https://github.com/subins2000/manglish/blob/master/app/src/test/java/subins2000/manglish/ml2enTest.java

**Comment by vachan-maker** [comment]
Ok. I changed ണ to N. I might have missed some letters, if there are please reply.

മേഖലയാണ് - mekhalayaa**Nu**
But ഇരട്ടിയോളവുമാണ് - iraTTiyolavumaa**N**
So do I need to add **u** after N?

**Comment by subins2000** [comment]
The right way to test this would be to use Android Studio to run the test to see if it pass. But by the looks of it, this looks good.

Also check out #16 . GoVarnam might replace the existing ml2en library, maybe in the future.

**Pull request merged**
